# Generated by Django 5.0.4 on 2024-05-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermodel',
            name='delivered_late',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='performancehistory',
            name='average_response_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performancehistory',
            name='fulfillment_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performancehistory',
            name='on_time_delivery_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performancehistory',
            name='quality_rating_avg',
            field=models.FloatField(null=True),
        ),
    ]
