# Generated by Django 4.2.3 on 2024-05-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0002_purchaseordermodel_delivered_late_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='issue_date',
            field=models.DateTimeField(null=True),
        ),
    ]
